version: '3'
services:
  postgres_farmacia:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: farmacia
      POSTGRES_HOST: postgres

volumes:
  postgres-volume: