micronaut:
  server:
    port: 8081
  application:
    name: farmacia.
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: false
  prometheus:
    sensitive: false

datasources:
  default:
    url: "jdbc:postgresql://localhost:5433/farmacia"
    username: "${JDBC_DATABASE_USERNAME:teste}"
    password: "${JDBC_DATABASE_PASSWORD:1234}"
    driverClassName: org.postgresql.Driver
jpa:
  default:
    schema-generate: CREATE_DROP
    entity-scan:
      packages: 'br.com.lucasmezuraro.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
